services:
  fastzero_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"    
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready"]
      test: ["CMD-SHELL", "sh -c 'pg_isready -U app_user -d app_db'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  fastzero_app:
    image: fastzero_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      fastzero_database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastzero_database:5432/app_db

volumes:
  pgdata: